name: bonnie sun kim
favicon: null
layout_spectrum: 1
typography_spectrum: 0.81681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1c1c1'
    - '#979797'
    - '#626262'
    - '#ededed'
    - '#000000'
  brandStrength: 0.5625
  lightness: 0.4375
  saturation: 0.6406692657619715
  rhythmicContrast: 0.25
purpose: []
