name: bonnie sun kim
favicon: null
layout_spectrum: 0.25149
typography_spectrum: 0.81681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#676773'
    - '#bcbebf'
    - '#8d919c'
    - '#ffdcbe'
    - '#0c090c'
  brandStrength: 0.3691811391618103
  lightness: 0.4375
  saturation: 0.6406692657619715
  rhythmicContrast: 0.12808623840101063
purpose: []
