name: bonnie sun kim
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1c1c1'
    - '#979797'
    - '#626262'
    - '#ededed'
    - '#000000'
  brandStrength: 1
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
